POST http://localhost:3000/usuarios
content-type: application/json
 
{
 "email":"email55@email.com",
 "nome":"teste",
 "telefone":9551234,
 "restricoes":"blabla",
 "tipo_usuario":"administrador"
}
 
###
 
GET http://localhost:3000/usuarios
 
###
 
GET http://localhost:3000/usuarios/1
 
###
 
PATCH http://localhost:3000/usuarios/1
content-type: application/json
 
{
 "email":"emailMUDOU@email.com",
 "nome":"teste",
 "telefone":9551234,
 "restricoes":"blabla",
 "tipo_usuario":"administrador"
}
 
###
 
DELETE http://localhost:3000/usuarios/4