POST http://localhost:3000/produtos
content-type: application/json
 
{
 "nome":"nomeProdutos",
 "descricao":"descricaoProduto",
 "imagem":"caminhoProduto",
 "ingredientes":"trigo, farinha, camarão",
 "usuarioId": 1
}
 
###
 
GET http://localhost:3000/produtos
 
###
 
GET http://localhost:3000/produtos/2
 
###
 
GET http://localhost:3000/produtos/usuario/2
 
###
 
GET http://localhost:3000/produtos/ingrediente/trigo
 
###
 
GET http://localhost:3000/produtos/semingrediente/leite

###
 
PATCH http://localhost:3000/produtos/9
content-type: application/json
 
{
 "nome":"nomeProdutosdois",
 "descricao":"descricaoProdutofff",
 "imagem":"caminhoProdutoaaaa",
 "ingredientes":"blablafsf",
  "usuarioId": 2
}
 
###
 
DELETE http://localhost:3000/produtos/1